FROM node:16-alpine as builder
WORKDIR '/app'
#COPY package.json .
COPY --chown=node:node ./package.json ./
RUN npm install
#RUN npm cache clean --force
#RUN npm install -g npm@latest --force
#RUN npm cache clean --force
#COPY . .
COPY --chown=node:node ./ ./
RUN npm run build
#CMD ["npm", "run", "start"]

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html

