FROM node:14.8-alpine as builder
WORKDIR '/app'
#COPY package.json .
COPY --chown=node:node ./package.json ./
RUN npm install
#COPY . .
COPY --chown=node:node ./ ./
RUN npm run build
#CMD ["npm", "run", "start"]

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html

